export default {
  obj: {
    Backquote: { rus: 'ё', eng: '`' },
    Digit1: { rus: '1', eng: '1', alternative: '!' },
    Digit2: { rus: '2', eng: '2', alternative: '@' },
    Digit3: { rus: '3', eng: '3', alternative: '#' },
    Digit4: { rus: '4', eng: '4', alternative: '$' },
    Digit5: { rus: '5', eng: '5', alternative: '%' },
    Digit6: { rus: '6', eng: '6', alternative: '^' },
    Digit7: { rus: '7', eng: '7', alternative: '&' },
    Digit8: { rus: '8', eng: '8', alternative: '*' },
    Digit9: { rus: '9', eng: '9', alternative: '(' },
    Digit0: { rus: '0', eng: '0', alternative: ')' },
    Minus: { rus: '-', eng: '-', alternative: '_' },
    Equal: { rus: '=', eng: '=', alternative: '+' },
    Backspace: { rus: 'Backspace', eng: 'Backspace', style: ['double', 'special'] },
    Tab: { rus: 'Tab', eng: 'Tab', style: ['sixfive', 'special'] },
    KeyQ: { rus: 'й', eng: 'q' },
    KeyW: { rus: 'ц', eng: 'w' },
    KeyE: { rus: 'у', eng: 'e' },
    KeyR: { rus: 'к', eng: 'r' },
    KeyT: { rus: 'е', eng: 't' },
    KeyY: { rus: 'н', eng: 'y' },
    KeyU: { rus: 'г', eng: 'u' },
    KeyI: { rus: 'ш', eng: 'i' },
    KeyO: { rus: 'щ', eng: 'o' },
    KeyP: { rus: 'з', eng: 'p' },
    BracketLeft: { rus: 'х', eng: '[' },
    BracketRight: { rus: 'ъ', eng: ']' },
    Backslash: { rus: '\\', eng: '\\' },
    Delete: { rus: 'DEL', eng: 'DEL', style: ['sixfive', 'special'] },
    CapsLock: { rus: 'Caps Lock', eng: 'Caps Lock', style: ['double', 'special'] },
    KeyA: { rus: 'ф', eng: 'a' },
    KeyS: { rus: 'ы', eng: 's' },
    KeyD: { rus: 'в', eng: 'd' },
    KeyF: { rus: 'а', eng: 'f' },
    KeyG: { rus: 'п', eng: 'g' },
    KeyH: { rus: 'р', eng: 'h' },
    KeyJ: { rus: 'о', eng: 'j' },
    KeyK: { rus: 'л', eng: 'k' },
    KeyL: { rus: 'д', eng: 'l' },
    Semicolon: { rus: 'ж', eng: ';' },
    Quote: { rus: 'э', eng: "'" },
    Enter: { rus: 'Enter', eng: 'Enter', style: ['double', 'special'] },
    ShiftLeft: { rus: 'Shift', eng: 'Shift', style: ['double', 'special'] },
    BackslashTwo: { rus: '\\', eng: '\\' },
    KeyZ: { rus: 'я', eng: 'z' },
    KeyX: { rus: 'ч', eng: 'x' },
    KeyC: { rus: 'с', eng: 'c' },
    KeyV: { rus: 'м', eng: 'v' },
    KeyB: { rus: 'и', eng: 'b' },
    KeyN: { rus: 'т', eng: 'n' },
    KeyM: { rus: 'ь', eng: 'm' },
    Period: { rus: 'б', eng: '.' },
    Comma: { rus: 'ю', eng: ',' },
    Slash: { rus: '/', eng: '/' },
    ArrowUp: { rus: '↑', eng: '↑', style: ['special'] },
    ShiftRight: { rus: 'Shift', eng: 'Shift', style: ['special'] },
    ControlLeft: { rus: 'Ctrl', eng: 'Ctrl', style: ['sixfive', 'special'] },
    MetaLeft: { rus: 'Win', eng: 'Win', style: ['special'] },
    AltLeft: { rus: 'Alt', eng: 'Alt', style: ['special'] },
    Space: { rus: ' ', eng: ' ', style: ['space'] },
    AltRight: { rus: 'Alt', eng: 'Alt', style: ['special'] },
    ControlRight: { rus: 'Ctrl', eng: 'Ctrl', style: ['sixfive', 'special'] },
    ArrowLeft: { rus: '←', eng: '←', style: ['special'] },
    ArrowDown: { rus: '↓', eng: '↓', style: ['special'] },
    ArrowRight: { rus: '→', eng: '→', style: ['special'] },
  },
};
